### ISSUE TITLE
USER STORY: Allow me to add friends and view their film lists.

### ISSUE THREAD

**Issue by AlexSmall96** [AlexSmall96/Film-Friends#10]
**Acceptance Criteria**

- Users can find each other on the app by username.
- Users can add and accept friend requests.
- Users can view friends' film lists, only seeing films the user has allowed others to see.
- Users are unable to see other users lists who have not accepted their friend requests.

**Tasks**

- [ ] Create a friend model in the database.
- [ ] Set up HTTP endpoint to allow users to make/accept friend requests.
- [ ] Create automated tests for HTTP endpoints.
- [ ] Set up front-end view for friend requests and acceptances.
- [ ] Create automated tests for front-end view.
