### ISSUE TITLE
USER STORY: Allow me to make recommendations to my friends.

### ISSUE THREAD

**Issue by AlexSmall96** [AlexSmall96/Film-Friends#11]
**Acceptance Criteria**

- Users can send a film recommendation to friends
- Users are unable to send recommendations to other users who have not accepted their friend requests.
- Receiver of recommendation can like and comment.

**Tasks**

- [ ] Create a recommendation model in the database.
- [ ] Set up an HTTP endpoint to allow users to send recommendations.
- [ ] Create automated tests for HTTP endpoints.
- [ ] Set up a front-end view for sending recommendations.
- [ ] Create automated tests for front-end view.
