### ISSUE TITLE
USER STORY: Allow me to view and customize my profile.

### ISSUE THREAD

**Issue by AlexSmall96** [AlexSmall96/Film-Friends#12]
**Acceptance Criteria**

- Users can edit their name and profile image.
- Users can change their email or password.

**Tasks**

- [x] Set up HTTP endpoint to allow users to update profile information.
- [x] Create automated tests for HTTP endpoints.
- [ ] Set up a front-end view for viewing and updating the profile.
- [ ] Create automated tests for front-end view.
