### ISSUE TITLE
USER STORY: Allow me to delete my account

### ISSUE THREAD

**Issue by AlexSmall96** [AlexSmall96/Film-Friends#13]
**Acceptance Criteria**

- Users can choose to delete the account.

**Tasks**

- [x] Set up HTTP endpoint to allow users to delete accounts.
- [x] Create automated tests for HTTP endpoints.
- [ ] Add delete functionality to the profile page.
- [ ] Create automated tests for front-end view.
