### ISSUE TITLE
Compatibility Ratings

### ISSUE THREAD

**Issue by AlexSmall96** [AlexSmall96/Film-Friends#14]
When users are friends on the app, calculate a score based on how similar their film ratings are.

**Tasks**

- [ ] Add functionality to automatically calculate a compatibility score when a friend request is accepted.
- [ ] Create automated tests for score calculation.
- [ ] Display compatibility score when a user views their friend's profile.
- [ ] Create automated tests for scores displayed on users' profiles.
