### ISSUE TITLE
USER STORY: Allow me to sign up to Film Friends

### ISSUE THREAD

**Issue by AlexSmall96** [AlexSmall96/Film-Friends#7]
**Acceptance Criteria**

- Users can sign up using a chosen email, username, and password.

**Tasks**

- [x]  Create a User model
- [x]  Set up HTTP endpoint for sign-up.
- [x]  Create automated tests for sign-up functionality
- [x]  Create a front-end view for signing up
- [x]  Create automated tests for front end view
