### ISSUE TITLE
USER STORY: Allow me to login to Film Friends with my account

### ISSUE THREAD

**Issue by AlexSmall96** [AlexSmall96/Film-Friends#8]
**Acceptance Criteria**

- After a user has signed up, they can log in to access the full functionality of the site.

**Tasks**

- [x]  Set up HTTP endpoint for log-in.
- [x]  Create automated tests for login functionality
- [ ]  Create front end view for logging in
- [ ]  Create automated tests for frontend view
