### ISSUE TITLE
USER STORY: Allow me to save films, rate them, mark them as watched and remove them from my list.

### ISSUE THREAD

**Issue by AlexSmall96** [AlexSmall96/Film-Friends#9]
**Acceptance Criteria**

- User can save a film to their watchlist, rate it, add notes, and mark it as watched.
- User can view all their films in a list.
- User can decide which of their films in the list can be viewed by others.

**Tasks**

- [x] Setup film model in database.
- [x] Setup HTTP endpoints for saving films, viewing film lists, updating films, and removing them from the list.
- [x] Create automated tests for HTTP endpoints.
- [ ] Create a frontend view for all film functionality.
- [ ] Create automated tests for front-end views.
